spring:
  profiles:
    active: test
  application:
    name: NomeProvisorioSite
  
  # Configuração de usuário padrão para desenvolvimento
  security:
    user:
      name: admin
      password: admin
# Configuração comum para todos os perfis
server:
  port: 8080